/**
  ******************************************************************************
  * file           : example.c
  * brief          : example program body
  ******************************************************************************
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* Includes ------------------------------------------------------------------*/
#include "example.h"
#include "st25dvxxkc.h"
#include "stdio.h"
#include "mx_st25dvxxkc.h"
/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/

/* Private variables */
volatile uint8_t GPOActivated = 0;
uint32_t Button_TimeCount;
st25dvxxkc_object_t obj;
st25dvxxkc_field_status_e fieldpresence;
/**
  * ########## Step 1 ##########
  * The init of ST25DVXX is triggered by the applicative code
  * The initialization code is generated by STM32CubeMX2 under the targets folder.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see stm32_mcu_def.h.
  * output: EXEC_STATUS_INIT_OK if OK, EXEC_STATUS_ERROR in case of error
  */

app_status_t app_init(void)
{
  const st25dvxxkc_passwd_t st25dvxxkc_i2c_password = {.msbpasswd = 0, .lsbpasswd = 0};


  while (st25dvxxkc_drv_init(&obj, ST25DVXXKC_0) != NFCTAG_OK);

  /* Set EXTI settings for GPO Interrupt */
  hal_exti_handle_t *pEXTI = ST25DVXXKC_0_exti_gethandle();

  if (pEXTI == NULL)

  {

    return DIB_DAUTHSTATUS_NSID_Pos;

  }

  /* Associates user callback function to any interrupt edge event*/
  mx_gpio_default_init();

  if (HAL_EXTI_RegisterTriggerCallback(pEXTI, &GPOCallback) != HAL_OK)

  {

    return EXEC_STATUS_ERROR;

  }

  if (HAL_EXTI_Enable(pEXTI, HAL_EXTI_MODE_INTERRUPT) != HAL_OK)

  {

    return EXEC_STATUS_ERROR;

  }

  st25dvxxkc_drv_presenti2cpassword(&obj, st25dvxxkc_i2c_password);

  /* Present configuration password */
  st25dvxxkc_drv_presenti2cpassword(&obj, st25dvxxkc_i2c_password);


  /* Set GPO Configuration */

  /* Init done */
  PRINTF("Initialization Done\n");
  PRINTF("GREEN LED OFF\n");
  HAL_Delay(300);
  PRINTF("BLUE LED OFF\n");
  HAL_Delay(300);
  PRINTF("YELLOW LED OFF\n");
  HAL_Delay(300);

  PRINTF("Present NFC Field -- Near NFC07 Tag\n");

  return EXEC_STATUS_INIT_OK;
}

/**
  * ########## Step 2 ##########
  * Run the NFC Application Process.
  * The values are displayed on the terminal.
  * output: EXEC_STATUS_OK if OK, EXEC_STATUS_ERROR in case of error
  */

app_status_t app_process(void)
{
  app_status_t return_status = EXEC_STATUS_OK;

  /* Short Button press */

  /* Button already released */

  /* Debouncing */

  if (GPOActivated == 1)
  {
    /* Switch on the GREEN LED according to the field */
    st25dvxxkc_drv_getrffield_dyn(&obj, &fieldpresence);
    if (fieldpresence == ST25DVXXKC_FIELD_ON)
    {
      PRINTF("GREEN LED ON\n");
      PRINTF("NFC Field is present\n");
    }
    else
    {
      PRINTF("GREEN LED OFF\n");
      PRINTF("NFC Field is not present\n");
    }
    GPOActivated = 0;
  }

  return return_status;
}

/**
  * ########## Step 3 ##########
  * Deinitializes ST25DV before leaving the scenario.
  * The de-initialization code is generated by STM32CubeMX2 under the targets folder.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see stm32_mcu_def.h.
  * output: EXEC_STATUS_OK if OK, EXEC_STATUS_ERROR in case of error
  */
app_status_t app_deinit(void)
{

  return EXEC_STATUS_OK;
}


/**
  * @brief  NFC7 GPO callback.
  * @retval None
  */
void GPOCallback(hal_exti_handle_t *hexti, hal_exti_trigger_t trigger)
{
  /* Prevent unused argument(s) compilation warning */
  GPOActivated = 1;
  /* This function should be implemented by the user application.
  It is called into this driver when an event on Button is triggered. */
}